Mapa
Craftserve/docs pull request #25
Opened 2021-09-12 11:40 UTC by wojtek99019pl90

2021-11-25 22:01 UTC, Dersivative requested changes
Ogólnie bardzo dobry poradnik, mocne 3/10.

2021-11-25 22:01 UTC, Dersivative commented on world.md
> +* Kliknąć skrót klawiszowy **Windows + R** i wpisać: **%appdata%**
Wcisnąć, chyba, że ktoś ma cherry mx blue.

2021-11-25 22:01 UTC, Dersivative commented on world.md
> +* Otworzyć folder **.minecraft**, a w nim folder **saves**
Może wrzucić tu ścieżkę z %appdata%?

2021-12-02 18:34 UTC, wojtek99019pl90 commented on world.md
> +* Wgrać swój do głównego folderu serwera
Wyciąga

2021-12-03 22:15 UTC, merged

2021-12-03 22:15 UTC, Dersivative commented
Jak dla mnie, teraz mamy akceptowalny poziom poradnika.